title: Yuankai
#tagline:          A short tagline
#description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url: 

# Owner/author information
owner:
  introduction:   You are the universe, expressing itself as a human for a little while.
  name:           Yuankai Wu
  avatar:         wu.jpg
#  bi
  #location:       Montreal, Canada
  email:          yuankai.wu@mcgill.ca
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  github: Kaimaoge
  instagram: 
  google_scholar: https://scholar.google.com/citations?user=L9b-8ZwAAAAJ&hl=en
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_verify: UA-151358120-1
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Blog
    url: /Blogs/
  - title: Research
    url: /projects/
  - title: Interest
    url: /interests/



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Canada/Pacific
future: true
pygments: true
#markdown: kramdown
markdown: kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

encoding: utf-8

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]


